//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWebProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleWebProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization does not found..
        /// </summary>
        public static string Authorization_AuthorizationDoesNotFound {
            get {
                return ResourceManager.GetString("Authorization_AuthorizationDoesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string Authorization_Edit_Title {
            get {
                return ResourceManager.GetString("Authorization_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization List.
        /// </summary>
        public static string Authorization_Index_Title {
            get {
                return ResourceManager.GetString("Authorization_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Record.
        /// </summary>
        public static string Common_AddNew {
            get {
                return ResourceManager.GetString("Common_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTI HUB Backend.
        /// </summary>
        public static string Common_AppName {
            get {
                return ResourceManager.GetString("Common_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin date must be greater than today.
        /// </summary>
        public static string Common_BeginDateMustbeGreaterThanToday {
            get {
                return ResourceManager.GetString("Common_BeginDateMustbeGreaterThanToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin date must be specified..
        /// </summary>
        public static string Common_BeginDateMustBeSpecified {
            get {
                return ResourceManager.GetString("Common_BeginDateMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Delete This Item.
        /// </summary>
        public static string Common_CannotDeleteThisItem {
            get {
                return ResourceManager.GetString("Common_CannotDeleteThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company does not found..
        /// </summary>
        public static string Common_CompanyDoesNotFound {
            get {
                return ResourceManager.GetString("Common_CompanyDoesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company must be specified..
        /// </summary>
        public static string Common_CompanyMustBeSpecified {
            get {
                return ResourceManager.GetString("Common_CompanyMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed due to collision..
        /// </summary>
        public static string Common_DateCollission {
            get {
                return ResourceManager.GetString("Common_DateCollission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record is going to be deleted. Do you want to continue ?.
        /// </summary>
        public static string Common_DeleteConfirm {
            get {
                return ResourceManager.GetString("Common_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration must be 1 day at least.
        /// </summary>
        public static string Common_DurationMustbeOneDayAtleast {
            get {
                return ResourceManager.GetString("Common_DurationMustbeOneDayAtleast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Common_Edit {
            get {
                return ResourceManager.GetString("Common_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be specified..
        /// </summary>
        public static string Common_EndDateMustBeSpecified {
            get {
                return ResourceManager.GetString("Common_EndDateMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel does not found..
        /// </summary>
        public static string Common_HotelDoesNotFound {
            get {
                return ResourceManager.GetString("Common_HotelDoesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location does not found..
        /// </summary>
        public static string Common_LocationDoesNotFound {
            get {
                return ResourceManager.GetString("Common_LocationDoesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid model.
        /// </summary>
        public static string Common_ModelValidationError {
            get {
                return ResourceManager.GetString("Common_ModelValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is not allowed.
        /// </summary>
        public static string Common_OperationNotAllowedError {
            get {
                return ResourceManager.GetString("Common_OperationNotAllowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider does not found..
        /// </summary>
        public static string Common_ProviderDoesNotFound {
            get {
                return ResourceManager.GetString("Common_ProviderDoesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider must be specified..
        /// </summary>
        public static string Common_ProviderMustBeSpecified {
            get {
                return ResourceManager.GetString("Common_ProviderMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item has relaed records. You can not delete this record.
        /// </summary>
        public static string Common_ToastrMessage_HasRelatedRecord {
            get {
                return ResourceManager.GetString("Common_ToastrMessage_HasRelatedRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully.
        /// </summary>
        public static string Common_ToastrMessage_Success {
            get {
                return ResourceManager.GetString("Common_ToastrMessage_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration_Edit_Title {
            get {
                return ResourceManager.GetString("Configuration_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration List.
        /// </summary>
        public static string Configuration_Index_Title {
            get {
                return ResourceManager.GetString("Configuration_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Currency.
        /// </summary>
        public static string ExchangeCurrency_Edit_Title {
            get {
                return ResourceManager.GetString("ExchangeCurrency_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Currency List.
        /// </summary>
        public static string ExchangeCurrency_Index_Title {
            get {
                return ResourceManager.GetString("ExchangeCurrency_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate.
        /// </summary>
        public static string ExchangeRate_Edit_Title {
            get {
                return ResourceManager.GetString("ExchangeRate_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate List.
        /// </summary>
        public static string ExchangeRate_Index_Title {
            get {
                return ResourceManager.GetString("ExchangeRate_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome !.
        /// </summary>
        public static string Home_Greeting_Header {
            get {
                return ResourceManager.GetString("Home_Greeting_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission amount must be specified..
        /// </summary>
        public static string HotelMarkup_CommissionAmountMustBeSpecified {
            get {
                return ResourceManager.GetString("HotelMarkup_CommissionAmountMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission type must be specified..
        /// </summary>
        public static string HotelMarkup_CommissionTypeMustBeSpecified {
            get {
                return ResourceManager.GetString("HotelMarkup_CommissionTypeMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Markup Is Already Defined..
        /// </summary>
        public static string HotelMarkup_DefaultMarkupAlreadyDefined {
            get {
                return ResourceManager.GetString("HotelMarkup_DefaultMarkupAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Markup.
        /// </summary>
        public static string HotelMarkup_Edit_Title {
            get {
                return ResourceManager.GetString("HotelMarkup_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel markup does not found..
        /// </summary>
        public static string HotelMarkup_HotelMarkupDoesNotFound {
            get {
                return ResourceManager.GetString("HotelMarkup_HotelMarkupDoesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Markup List.
        /// </summary>
        public static string HotelMarkup_Index_Title {
            get {
                return ResourceManager.GetString("HotelMarkup_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu_Edit_Title {
            get {
                return ResourceManager.GetString("Menu_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu List.
        /// </summary>
        public static string Menu_Index_Title {
            get {
                return ResourceManager.GetString("Menu_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role_Edit_Title {
            get {
                return ResourceManager.GetString("Role_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role List.
        /// </summary>
        public static string Role_Index_Title {
            get {
                return ResourceManager.GetString("Role_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Sale.
        /// </summary>
        public static string StopSale_Edit_Title {
            get {
                return ResourceManager.GetString("StopSale_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Sale List.
        /// </summary>
        public static string StopSale_Index_Title {
            get {
                return ResourceManager.GetString("StopSale_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Sale does not found..
        /// </summary>
        public static string StopSale_StopSaleDoesNotFound {
            get {
                return ResourceManager.GetString("StopSale_StopSaleDoesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User_Edit_Title {
            get {
                return ResourceManager.GetString("User_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User List.
        /// </summary>
        public static string User_Index_Title {
            get {
                return ResourceManager.GetString("User_Index_Title", resourceCulture);
            }
        }
    }
}
